server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled : true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true

    username: root
    password: fjqmqjtm
    name: bigcare_dev
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 90
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
